app = "afd-wapp-bot"
primary_region = "lhr"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  [http_service.concurrency]
    type = "requests"
    hard_limit = 25
    soft_limit = 20

[checks]
  [checks.health]
    grace_period = "30s"
    interval = "15s"
    method = "GET"
    path = "/health"
    port = 8080
    timeout = "10s"
    type = "http"

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
